version: '3'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
  seed:
    build: ./seed
    links:
      - mongodb_container
  brio_test:
    restart: always
    build: .
    ports:
      - "8080:8080"
volumes:
  mongodb_data_container: